management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8084
spring:
  application:
    name: gateway

  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: bus
          uri: lb://BUS-BOOKING-SERVICE
          predicates:
            - Path=/bus-booking-service/**
        - id: fund
          uri: lb://FUND-TRANSFER-APPLICATION
          predicates:
            - Path=/fund-transfer/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/